# Generated by Django 5.0.3 on 2024-03-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_long_description_book_page_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='page_count',
            field=models.IntegerField(default=0),
        ),
    ]
